$ANSIBLE_VAULT;1.1;AES256
66636262393135366230376635343734616563643665366666613931303465636236353637623031
3462623530313934363730656438353037633932346135360a343733393434326463663661346632
63613331373066626135343837333038333639303634383836643134656239383064316133353764
3565633065643535310a353030656464613065633864656636376661316162666262336663383964
36376633326364363263373564626164323739336536663866653066353936363436326333666364
65363264333331303562643435346636653930633934323263313730313433373331363563636232
35306335383236663036383132343534643638613131363637386364363338363030363531353263
64643138346436326365383731343836393137373738373535323466323238666264366564646165
30333232316661363364656638653265356237313662353965373163393434653165
