- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Create SSL directory
  file:
    path: "{{ ssl_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Generate private key
  openssl_privatekey:
    path: "{{ selfsigned_key }}"
    size: 2048
    mode: '0600'
  become: yes

- name: Generate CSR
  openssl_csr:
    path: "{{ selfsigned_csr }}"
    privatekey_path: "{{ selfsigned_key }}"
    common_name: "{{ domain_name }}"
    subject_alt_name:
      - "DNS:{{ domain_name }}"
    country_name: "BY"
    state_or_province_name: "Minsk"
    locality_name: "Minsk"
    organization_name: "DevOps Team"
    mode: '0644'
  become: yes

- name: Generate self-signed certificate
  openssl_certificate:
    path: "{{ selfsigned_crt }}"
    privatekey_path: "{{ selfsigned_key }}"
    csr_path: "{{ selfsigned_csr }}"
    provider: selfsigned
    selfsigned_not_after: "+365d"
    mode: '0644'
  become: yes

- name: Copy Nginx virtual host configuration
  template:
    src: app.devops.local.conf.j2
    dest: "{{ nginx_conf_way }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart Nginx

- name: Enable Nginx virtual host
  file:
    src: "{{ nginx_conf_way }}"
    dest: "{{ nginx_vh_way }}"
    state: link
  become: yes
  notify: Restart Nginx

- name: Remove default site
  file:
    path: "{{ nginx_default_site }}"
    state: absent
  become: yes
  notify: Restart Nginx

- name: Create Nginx log directories
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes