$ANSIBLE_VAULT;1.1;AES256
30303161363537666430376463666635663039343934303763373837326663333263376334383661
6665323737623365333038386561646132623937336437610a316561313464666661363836356464
38356663663831666666353462646633313238303765323031633765323935383438313637383934
3038373463313662330a396238363333636662626231653735663730643232666335616636373030
33643931383563626435396338376361366334333163653935313536323537636566383538323264
65616164363139623230333166346462366531343132663565303064386636323064353033316237
35336261656263636465316466386161623961613665313463373939363937383335636264636434
35376532656135653637303739343039396432373536646633373833303936306362633639343733
31623234333461383463386135306665353361393536643565613739643066316134
