---
- name: Create logs directory for scripts
  file:
    path: "{{ script_log_dir }}"
    state: directory
    owner: devops
    group: devops
    mode: '0755'
  become: yes

- name: Copy setup.sh script # there is ansible.builtin.pip module for requirements.txt setup (я просто копирую скрипт, который нужен по заданию, установка зависимостей в роли application)
  template:
    src: setup.sh.j2
    dest: "{{ app_dir }}/setup.sh"
    owner: devops
    group: devops
    mode: '0755'
  become: yes

- name: Create backups directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: devops
    group: devops
    mode: '0755'

- name: Copy backup.sh script
  template:
    src: backup.sh.j2
    dest: "{{ backup_dir }}/backup.sh"
    owner: devops
    group: devops
    mode: '0755'
  become: yes

- name: Install backup cron job
  cron:
    name: "Daily database backup"
    minute: "0"
    hour: "2"
    job: "{{ app_dir }}/backup.sh >> {{ cron_backup }} 2>&1"
    user: devops
  become: yes
