---
- name: Create logs directory for scripts
  file:
    path: "var/log"
    state: directory
    owner: devops
    group: devops
    mode: '0755'
  become: yes
  become_user: devops

- name: Copy setup.sh script
  template:
    src: setup.sh.j2
    dest: "{{ app_dir }}/setup.sh"
    owner: devops
    group: devops
    mode: '0755'
  become: yes
  become_user: devops

- name: Create backups directory
  file:
    path: "/var/task1/backups"
    state: directory
    owner: devops
    group: devops
    mode: '0755'
  become: yes

- name: Copy backup.sh script
  template:
    src: backup.sh.j2
    dest: "{{ app_dir }}/backup.sh"
    owner: devops
    group: devops
    mode: '0755'
  become: yes
  become_user: devops

- name: Install backup cron job
  cron:
    name: "Daily database backup"
    minute: "0"
    hour: "2"
    job: "{{ app_dir }}/backup.sh >> /var/backups/cron_backup.log 2>&1"
    user: devops
  become: yes
