$ANSIBLE_VAULT;1.1;AES256
34633431663139333066303338643165643437313562353635353761333230353132353339333537
6536316631316263633332396639643539643431656165330a366337656262323634323937623336
36356366623461303334616663643930356130626231346361653339633265666237353135363933
6261653463313932640a616531613463666565626666393563623433636531373737653865653630
36313065343863323266313738323230616565623735633232626139353535323830313466323635
62643836313366656633373330626566396261653331616463643236616566373566666364386332
30303534396564373962643134343161346139323230636130333334313464666363613933363436
64393131396662366530626130356239353434383839636430383234343331643737643038353439
34353933383033336161373866396166346633383330343030303534616264386261
