- name: Install PostgreSQL and dependencies
  apt:
    name: [postgresql, postgresql-contrib, python3-psycopg2]
    state: present

- name: Create PostgreSQL log directory
  file:
    path: "{{ postgresql_log_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'
  become: yes

- name: Ensure PostgreSQL cluster exists
  command: pg_createcluster 14 main --start
  args:
    creates: "{{ db_config }}"
  register: cluster_created
  become: yes

- name: Copy pg_hba.conf template
  template:
    src: pg_hba.conf.j2
    dest: "{{ db_pg_hba }}"
    owner: root
    group: root
    mode: '0644'
  register: hba_changed

- name: Configure listen_addresses in postgresql.conf
  lineinfile:
    path: "{{ db_config }}"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
  register: listen_changed

- name: Configure port in postgresql.conf
  lineinfile:
    path: "{{ db_config }}"
    regexp: '^#?port\s*='
    line: "port = 5432"
  register: port_changed

- name: Enable logging collector
  lineinfile:
    path: "{{ db_config }}"
    regexp: '^#?logging_collector\s*='
    line: "logging_collector = on"
  register: log_collector_changed

- name: Set log directory
  lineinfile:
    path: "{{ db_config }}"
    regexp: '^#?log_directory\s*='
    line: "log_directory = '{{ postgresql_log_dir }}'"
  register: log_dir_changed

- name: Set log filename pattern
  lineinfile:
    path: "{{ db_config }}"
    regexp: '^#?log_filename\s*='
    line: "log_filename = 'postgresql-%Y-%m-%d.log'"
  register: log_file_changed

- name: Configure what to log
  lineinfile:
    path: "{{ db_config }}"
    regexp: '^#?log_statement\s*='
    line: "log_statement = 'mod'"
  register: log_statement_changed

- name: Restart PostgreSQL if any configuration changed
  systemd:
    name: postgresql
    state: restarted
    enabled: yes
  become: yes
  when: >
    cluster_created.changed or
    hba_changed.changed or
    listen_changed.changed or
    port_changed.changed or
    log_collector_changed.changed or
    log_dir_changed.changed or
    log_file_changed.changed or
    log_statement_changed.changed

- name: Create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: LOGIN
    login_user: postgres
  become: yes
  become_user: postgres

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    login_user: postgres
  become: yes
  become_user: postgres